### ISSUE TITLE
How can I center the pin and the animated view in the (AnimatedViews.js) example , when pin is pressed?

### ISSUE THREAD

**Issue by hugomosh** [react-native-community/react-native-maps#1083]
I had a custom implementation of the AnimatedViews.js
But I am struggling to figure it out how to center the pin when it is pressed and also center the proper animatedview.
Am I missing something? **How can i manually/force the animation to the index i want??**
 I have tried to update the index in the onPress : 
```js
<MapView.Marker
	key={marker.id}
	coordinate={marker.coordinate}
        onPress={(e) => {
	console.log('Press')
	const {index} = this.state;
	if (index !== i) {
		this.setState({index: i});
	}
}}>
```

But it doesn't update the pin properly,  nor animate to the view.
Any thoughts?
Thanks
Also, in iOS is working smoothly but in android is kind of slow. Is this fixable?

**Comment by hugomosh** [comment]
I am having trouble understanding the Animation. Is there a place where it is explained in detail?

**Comment by dscx** [comment]
I'm having this issue too. Did you ever figure it out?

**Comment by hugomosh** [comment]
I ended up using a react native carousel plugin over the map

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
