### ISSUE TITLE
MapView.Marker onSelect support for Android

### ISSUE THREAD

**Issue by stinju** [react-native-community/react-native-maps#114]
Is MapView.Marker onSelect support for Android on your short-term roadmap?

**Comment by alvelig** [comment]
https://stackoverflow.com/questions/29345928/changing-the-icon-of-google-maps-marker-while-its-selected
https://stackoverflow.com/questions/29740839/how-to-select-and-deselect-a-marker-in-google-maps-in-android

**Comment by tobiasf** [comment]
Any updates on this? Is MapView.Marker going to get onSelect and onDeselect support for Android too?

**Comment by alvelig** [comment]
@tobiasf Not likely. It's out of the focus as far as I know. But I left those links if someone wants to contribute.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by chrise86** [comment]
Just ran into this issue. When you say those events are not supported on Android, does that actually mean Google Maps? As it does not seem to work for me on iOS using Google Maps.
