### ISSUE TITLE
Still error: cannot find symbol

### ISSUE THREAD

**Issue by chankung** [react-native-community/react-native-maps#1145]
Hi,

I have add **import com.airbnb.android.react.maps.MapsPackage;** to my MainApplication already.
But it still  error: cannot find symbol.

Please help me.

**Comment by prontiol** [comment]
@chankung I solved this by adding `Symbol` polyfill from [core-js](https://github.com/zloirock/core-js).

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
