### ISSUE TITLE
[iOS] Disabling moveOnMarkerPress hides marker

### ISSUE THREAD

**Issue by viktorsec** [react-native-community/react-native-maps#1155]
```
<MapView
  initialRegion={{
    latitude: this.props.latitude,
    longitude: this.props.longitude,
    latitudeDelta: 0.00922,
    longitudeDelta: 0.00421,
  }}
  moveOnMarkerPress={false}
>
  <MapView.Marker
    coordinate={{
      latitude: this.props.latitude,
      longitude: this.props.longitude,
    }}
    title="Hello"
  />
</MapView>
```

Deleting `moveOnMarkerPress={false}` makes the marker visible again.

react-native: 0.41.2
react-native-maps: 0.13.0

**Comment by lelandrichardson** [comment]
@viktorsec interesting. This prop is labeled as "android only" you say you're getting this issue on ios?

**Comment by viktorsec** [comment]
Correct. We are building for both Android and iOS and I encountered the issue on iOS.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
