### ISSUE TITLE
geo fence with polygons?

### ISSUE THREAD

**Issue by hardtailbrown1** [react-native-community/react-native-maps#1222]
is anybody using the polygons as geofences? seems like it would be relatively easy if a method were added that checks if a point is contained within it. my understanding is that the google geometry library has a function to determine this, but I am fairly new to react native and not sure what the easiest way to accomplish it is since that would require porting it to react native. thx

**Comment by Kosai106** [comment]
Oh yes please!

I'm needing exactly this feature right now. (Or a function to get all markers in x radius around a location.) I've looked into what would be the best way to approach something like this, but I have to admit I'm stuck.

**Comment by Anandks1993** [comment]
Try this https://www.npmjs.com/package/react-native-geo-fencing package. With this we can easily make use of geofencing.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
