### ISSUE TITLE
Android minDelta and maxDelta not working

### ISSUE THREAD

**Issue by kyangy** [react-native-community/react-native-maps#1282]
I have MapView set with minDelta and maxDelta but it only seems to work in ios.  In android my map is too zoomed, is there any other way I can make this work?

**Comment by babenzele** [comment]
Try setting zoom with `latitudeDelta` and `longitudeDelta` in the `region` prop:
https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md#types

I don't even see `minDelta` or `maxDelta` on the list of props for MapView:
https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md

**Comment by babenzele** [comment]
Ah, I see min and max delta in [MapView.js](https://github.com/airbnb/react-native-maps/blob/master/lib/components/MapView.js)

**Comment by kyangy** [comment]
@babenzele Thank you for helping me out! How do you determine the latitudeDelta/longitudeDelta? And is this the only way to control how much the map is zoomed for android?

**Comment by babenzele** [comment]
I used the values from the [expo demo](https://docs.expo.io/versions/v15.0.0/sdk/map-view.html). 

[latitudeDelta](https://developer.apple.com/reference/mapkit/mkcoordinatespan/1452417-latitudedelta) and [longitudeDelta](https://developer.apple.com/reference/mapkit/mkcoordinatespan/1452573-longitudedelta)

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
