### ISSUE TITLE
Markers overlay the map and are not moving

### ISSUE THREAD

**Issue by Maxwell2022** [react-native-community/react-native-maps#1288]
Here is the demo of the issue:

![map issue](https://cloud.githubusercontent.com/assets/670701/25601914/e9759854-2f32-11e7-8b6d-26dbe7f35434.gif)

On top of having the marker at the top left corner (https://github.com/airbnb/react-native-maps/issues/678), I can see markers that are very far from the location the map is zoomed in, and they are not moving at all

Using:
- react-native 0.42.0
- react-native-map 0.14.0

**Comment by masiamj** [comment]
+1

**Comment by Maxwell2022** [comment]
still happening with react-native-map 0.15.0

**Comment by KrauseFx** [comment]
I also experience that, but it only randomly happens, and not all the time. Do you have a reliable way to reproduce?

I tried switching to Google Maps, which seems to fix the annotation bug, and also fixes touch gestures to zoom even when you drag on a marker, but the Google Maps version of this library has a known bug that callouts aren't tappable...

**Comment by Maxwell2022** [comment]
It's also happening randomly for me :/

**Comment by chapeljuice** [comment]
Happening for me too! What is going on here??

![map-marker](https://cloud.githubusercontent.com/assets/862642/26699524/150f0686-46cf-11e7-9714-9fdd8ee074de.gif)

Code here:
https://gist.github.com/chapeljuice/cd61e6e57819eaf959c7635f2257a13c

**Comment by grundmanise** [comment]
Had the same issue with `MapView.Marker.Animated` after `animateToRegion` so I've wrapped `animateToRegion` inside `setTimeout(() => {}, 0);` -- and it fixed the issue for me.

**Comment by zakster12** [comment]
@grundmanise I tried with your suggestion but it doesn't work. Do you have any other ideas?

**Comment by zakster12** [comment]
@Maxwell2022 did you find any solution to this?

**Comment by chapeljuice** [comment]
@zakster12 for me it was as simple as removing `onRegionChange={this.onRegionChange}` from my map.

**Comment by jonathanwmaddison** [comment]
I'm also having this problem. I am mapping over an array of markers and rendering a custom Marker like this:
```
<Mapview.Marker>
   <Image />
   <Image />
</MapView.Marker>
```
Some of the markers will render in the correct spot, and others will stick on the screen and render in random locations. If I render without the images, the markers behave normally. We can also pass in a random key when mapping over the array but this is not a good solution since it causes the markers to flicker anytime state changes.

**Comment by zolrath** [comment]
I'm getting the same behavior when I change the maps location and clear my markers. Instead of the markers disappearing, a ghost image of them stays on the screen like in the original reports gif.

**Comment by brmk** [comment]
I have the same behavior in the same situation as @zolrath has noted
Any ideas how to prevent this from happening?

**Comment by rborn** [comment]
@brmk do you have multiple children in markers? I think they accept only one so you might need to wrap them in a `View`

**Comment by superDev610** [comment]
I guess this may happen when you use Mapview. Animated or not?
Let me know.

**Comment by bramus** [comment]
Yes, it happens with a normal `<MapView />`. I found it to be happening after a refreshing a set of locations which yield a re-render of the map's markers: I have an app which starts up and displays a set of locations. All is displayed correctly. When the user then logs in, a new list of locations is fetched (the new list contains the original locations + a few extra ones). It's at this moment that the entire map re-renders, and that the “floating ghost markers” appear at a static position on top the map (cfr. the gif at the very top of this issue).

---

For reference: my markers are regular `<MapView.Marker>` instances with a custom Component as its child. The marker itself has `coordinate`, `identifier`, `key`, and `onPress` props.

````js
{Object.entries(locations).map(entry => {
	const [locationId, location] = entry;
	return (
		<MapView.Marker
			identifier={locationId}
			key={locationId}
			coordinate={{
				latitude: parseFloat(location.lat),
				longitude: parseFloat(location.lng),
			}}
			onPress={this.onMarkerPress}
		>
			<LocationDonut location={location} size={36} />
		</MapView.Marker>
	);
})}
````

---

Some observations about these "floating ghost markers":

1. They are placed on correct positions relatively to each other: if I were to zoom out the map so that all markers would fit, the constellation I would see then is the same constellation of the floating ghost markers — e.g. it's not that they're positioned wrongly: they're positioned correctly but just not the current zoom level of the map.

2. They disappear from their ghost position the moment you pan the map/zoom to the location where they would normally appear.

I hope this helps in the further investigation of this issue.

**Comment by ewein** [comment]
I'm having this issue as well on v0.19.0 with custom image markers.

**Comment by rborn** [comment]
@angineering can you post some code? Also can you try with the last version of the module from master git and not npm ?

**Comment by strrife** [comment]
Happens to me too but only with a custom image marker (ios). The marker sticks at the top left corner and goes away only when I navigate/zoom to a region containing it.
![image](https://user-images.githubusercontent.com/5725161/39968085-07c2544e-56d0-11e8-9e51-77d41f7ec13c.png)

**Comment by rborn** [comment]
Very old issue, closing.
