### ISSUE TITLE
How to work around App "won't run unless you upgrade Google Play Services"

### ISSUE THREAD

**Issue by hiddentao** [react-native-community/react-native-maps#1297]
Just putting this ticket here in case somebody else runs into this error.

Just tried my app on a brand new Android device (S6). I got a `CameraUpdateFactory is not initialized` error - when I dismissed it I saw this within the maps view:

![screenshot_20170503-143359](https://cloud.githubusercontent.com/assets/266594/25671742/fdbf51dc-3028-11e7-86a1-8e10b78437a1.jpg)

If you see this it means the user needs to upgrade the _Play Services_ app before the map will show.

My workaround was to  use [react-native-google-api-availability-bridge](https://github.com/UCSD/react-native-google-api-availability-bridge) to check to see if Play Services need to be updated when my app first starts up, and then prompting the user to do so.

**Comment by zengyanzi** [comment]
is there anything happend after you click the button of "update"
or do you use the android studio instead of a physical devices?

**Comment by hiddentao** [comment]
@zengyanzi On device it launches the Play Store to the "Google Play Services" app. Didn't try on the simulator.

**Comment by zengyanzi** [comment]
@hiddentao  thanks
I finally work out by update the android studio Google play services to the latest version.
Thanks again

**Comment by viktorsec** [comment]
Any updates on this?

**Comment by dramaking** [comment]
I think it is related to this PR:
https://github.com/airbnb/react-native-maps/pull/1443

In my case, I called "fitToCoordinates" method when the map first loads. And because the google play service is not up to date, the "map" object is null, which causes this error.

The solution is to do a null check for the map in any region related method.

**Comment by 1uokun** [comment]
+1

**Comment by kevinkevw** [comment]
It will be great if comes with a function to check if the service is available or let us customize this gray screen. Not just outdated play service will trigger this, some countries (e.g. China ) which blocked the service will need to find some alternative ways to present when the map is not available as well.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by GeovaneDaSilva** [comment]
You need to create a new emulator that has Google Play, as they are complete and have support for this new version.
Create a Pixel 2 API 30 emulator.
