### ISSUE TITLE
Overlay text on Polygon

### ISSUE THREAD

**Issue by maximromanyuk** [react-native-community/react-native-maps#1319]
I want to write some text on polygon like on photo, how can I do it?
![13](https://cloud.githubusercontent.com/assets/8741333/25947572/ba8d4af0-3658-11e7-81f1-3df839bcd79f.png)

Currently `MapView.Polygon` hasn\`t `child` prop

**Comment by Fantasim** [comment]
MapView.Polygon hasn't still child prop ?

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
