### ISSUE TITLE
Can I show maps on 3d mode?

### ISSUE THREAD

**Issue by xuho** [react-native-community/react-native-maps#1373]

**Comment by VincentCATILLON** [comment]
+1

**Comment by eiosca** [comment]
Hi, Only for iOS:
File: RCTConvert+AirMap.m L30:0

```
RCT_ENUM_CONVERTER(MKMapType, (@{
  @"standard": @(MKMapTypeStandard),
  @"satellite": @(MKMapTypeSatellite),
  @"hybrid": @(MKMapTypeHybrid),
  @"hybridFlyover": @(MKMapTypeHybridFlyover),
}), MKMapTypeStandard, integerValue)
```

And file MapView.js L28:0
```
const MAP_TYPES = {
  STANDARD: "standard",
  SATELLITE: "satellite",
  HYBRID: "hybrid",
  TERRAIN: "terrain",
  HYBRIDFLYOVER: "hybridFlyover",
  NONE: "none" 
};
```

After that you can use "hybridFlyover" mode. Enjoy!

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
