### ISSUE TITLE
Polygon onPress erratic behavior

### ISSUE THREAD

**Issue by alizahid** [react-native-community/react-native-maps#1392]
I wanted my `Polygon` to have a `Callout` but seeing as there's nothing in the API, I sort of made my own. The solution is having a `Polygon` and a `Marker` inside a `View` and calling the `Marker`'s `showCallout()` from `Polygon`'s `onPress` method. Problem is, the thing is rather erratic.

Here's a video showing what happens: https://hostd.in/bijli/polygon-onpress.mp4

You can't see the taps, but when I tap once, the event fires twice (confirmed by logs). There's a boolean check for hide and show, and sometimes it takes two taps to show the `Callout`, and other times, tapping once shows and immediately hides the `Callout`.

This behavior only occurs when there's multiple `Polygon`s. Everything seems fine with just one.

Link to the code: https://snack.expo.io/H1L9ClUGW

Expo client doesn't have `react-native-maps`, so it won't run, though.

Any thoughts?

**Comment by alizahid** [comment]
It would appear that the second (or rather, first) `onPress` comes from the user tapping the invisible `Marker`. Which makes the question easier: is there a `tappable` property for `Marker` to prevent it from showing the `Callout`?

**Comment by Purphict** [comment]
I went into the polygon function and changed the last statement to `polygon.open = null;` instead of `polygon.open = !polygon.open;`, which seems to fix the issue: http://recordit.co/5s0v9Tt44E

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
