### ISSUE TITLE
What is the unit of EdgePadding?

### ISSUE THREAD

**Issue by lsps9150414** [react-native-community/react-native-maps#1406]
What is the unit of EdgePadding? Seems it is not px?

**Comment by yonahforst** [comment]
Looks like it's in screen points:
https://developer.apple.com/documentation/mapkit/mkmapview/1452461-setvisiblemaprect

**Comment by jasperkuperus** [comment]
It seems to be different on iOS and on Android (Yes, I'm using Apple maps on iOS and Google maps on Android). It even seems to be different between different Android devices. Could anyone provide some more explanation on this?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
