### ISSUE TITLE
Is it possible to toggle/show a particular polyline?

### ISSUE THREAD

**Issue by rexlow** [react-native-community/react-native-maps#1504]
I have an array of polyline arrays which looks like this.

```
[
   [
       {lat: ' ', long: ' '},
       {lat: ' ', long: ' '},
       {lat: ' ', long: ' '},
   ]
   [
       {lat: ' ', long: ' '},
       {lat: ' ', long: ' '},
       {lat: ' ', long: ' '},
   ]
]
```

And this is how I render both of the polylines
```
{rootCoordinates.map((coordinates, index) => ( // coordinates from redux state
     <MapView.Polyline
          key={index}
          coordinates={coordinates}
          strokeColor={index % 2 === 0 ? "#19B5FE" : "#53D769"}
          strokeWidth={5}
          /> 
 ))}
```

My question is, is there a way to toggle just one polyline off, without having to mess with the array from my redux store? I know we can just easily exclude one of the child array when the button is pressed, thus `hiding` the polyline but is this a good approach?

**Comment by EricPKerr** [comment]
You would have a separate `this.state.activeIndex` (or through props if it's in Redux) and then inside the map you would do

```
{rootCoordinates.map((coordinates, index) => (
  if(this.state.activeIndex !== index) return;
  ...
))];
```
Or, the cleaner way to do it would be:

`<MapView.Polyline coordinates={rootCoordinates[this.state.activeIndex]} ... />`

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
