### ISSUE TITLE
Snapshot double vision: displays low opac overlay of map flipped vertically

### ISSUE THREAD

**Issue by JKonTiki** [react-native-community/react-native-maps#1645]
When I take a snapshot on android (haven't tried on iOS), you can see that, at a low opacity, it is overlaid by a vertically flipped version of itself. The container displaying the MapView has been stripped of most other Views, and I guess this could have to do with a number of things running through my app (e.g. navigation).

I'm wondering if anyone has experienced this, or would love to hear a gut reaction to why this might be happening.

Thanks!

![download](https://user-images.githubusercontent.com/20776648/30406748-9289c4f4-98a8-11e7-82ed-80c825f13cc0.png)

**Comment by JKonTiki** [comment]
setting showBuildings={false} does seem to squash the bug, still wondering where it may have come from though.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
