### ISSUE TITLE
[Request] Time map feature

### ISSUE THREAD

**Issue by nathanwaters** [react-native-community/react-native-maps#1660]
Mapbox just created this prototype: https://blog.mapbox.com/a-new-kind-of-map-its-about-time-7bd9f7916f7f

Demo: https://www.mapbox.com/labs/timemap/search/

Would be awesome to have that as an optional UI/UX

**Comment by kytwb** [comment]
I think this is out of the scope of this module, or at least very low priority regarding the other existing issues this repository have.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
