### ISSUE TITLE
Marker callout closed when content changes (Android)

### ISSUE THREAD

**Issue by nickdaugherty** [react-native-community/react-native-maps#172]
If a re-render causes a Marker's callout to change, either via the `title` and `description` properties, or a custom callout child element, a previously open callout will unexpectedly be closed.

The expected behavior is for the previously open callout to remain open, while reflecting the changes.

An example use case would be showing the current distance from the user to a marker in a custom callout. User opens the callout, and as they move, the callout is updated to reflect the changing distance. Currently, this scenario will cause the callout to be closed as soon as the map is re-rendered in response to a location update.

Related to #34 and the Note here (Android) https://developers.google.com/maps/documentation/android-api/infowindows#custom_info_windows

On iOS, the callout is not closed, but it doesn't appear to update either.

**Comment by DennisMG** [comment]
Did find a workaround for this?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
