### ISSUE TITLE
How draw one polyline with different strokeColor for segments of the polyline? 

### ISSUE THREAD

**Issue by jan-happy** [react-native-community/react-native-maps#1805]
I have an array of coordinates recorded on a car ride and each coordinate has a property "strokeColor" which is representing the speed of the car like this:
`[ { strokeColor: "#FB8F01", latitude: 7.214327025, longitude: 51.40323151 },
 { strokeColor: "#003F01", latitude: 7.214325025, longitude: 51.40343151 },  
{ strokeColor: "#003FFF", latitude: 7.215325025, longitude: 51.40443151 },...]`
Now I want to display the different colors in one PolyLine that changes color according to the speed the car had at that segment of the recording.
I've tried this idea: [https://github.com/airbnb/react-native-maps/issues/1593](url) but I need to have one connected path of colourful segments, not multiple PolyLines next to each other. 
Any clues on how to solve this? Thanks!

**Comment by alvelig** [comment]
Is that what you are trying to archive? https://github.com/wdanxna/GradientPolyline/

**Comment by jan-happy** [comment]
@alvelig: Yes, although one solid colour per segment (from one coordinate to the other) would be sufficient. In the meantime I added one polyline every two coordinates. But I wonder how the performance will be if I add hundreds of seperate polylines on the map. What do you think?

**Comment by meknil** [comment]
I am interested in gradient polylines too.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
