### ISSUE TITLE
Point is not scaled according to screen

### ISSUE THREAD

**Issue by thatsmydoing** [react-native-community/react-native-maps#190]
This is for the Android maps, I don't know the behavior on iOS. I don't know what the expected behavior is but the point returned in the onPress event needs to be scaled to get RN's resolution independent pixels. This is needed for positioning elements absolutely.

```
let {x, y} = event.nativeEvent.position;
let {scale} = Dimensions.get('window');
let actualX = x / scale;
let actualY = y / scale;
```

**Comment by rborn** [comment]
@thatsmydoing I know it's very late, but this is what you need? https://github.com/react-community/react-native-maps/pull/1851

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
