### ISSUE TITLE
Where is the icon that Google Maps uses by default?

### ISSUE THREAD

**Issue by salbatore** [react-native-community/react-native-maps#1935]
### Is this a bug report?

NO

### Steps to Reproduce

All versions

### Expected Behavior

When I have hundreds of markadores the app is very slow.

### Question

Where is the icon that Google Maps uses by default? I want to edit it from the root,  is no way to get that fluidity by adding a vector, image or font in the <marker>.

Is it possible to modify that root icon? ... Is that marker somewhere?

**Comment by salbatore** [comment]
@rborn you are my hero :D.... thanks!!!!

**Comment by rborn** [comment]
@salbatore did you find where they are on android?

**Comment by salbatore** [comment]
Nop... i dont see.. :P... this weekend i will search in depth

**Comment by salbatore** [comment]
Good afternoon ... do you know where I can change the dimensions of the default markers?... I'm going crazy, haha

**Comment by rborn** [comment]
nope

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
