### ISSUE TITLE
Marker Callout position moves around , bug or need a workaround

### ISSUE THREAD

**Issue by jeveloper** [react-native-community/react-native-maps#198]
Hello and thank you for making this library !

I'm using calloutOffset to slightly move it over the pin (it hides very well)

```
<MapView.Marker
          ref="m1"
          flat={true}
          coordinate={{latitude: this.props.annotation.latitude, longitude: this.props.annotation.longitude}}
          calloutOffset={{ x: 0, y: 200 }}
          >

```

However when tapping/clicking on the image pin (its a wide image) , what happens is callout also moves to the left or right (x axis).

I have a feeling that i need to capture x, y where the person tapped it and change calloutOffset dynamically before its displayed. is that correct? or is this a bug?
ideally id like to see callout appear as it should, same position above (x= 0 ) pin.

Thank you

**Comment by darren1982** [comment]
I am seeing the same issue. Can't figure out why the call out position seems to move to left or right

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
