### ISSUE TITLE
Map is cut off on Android despite using absoluteFillObject

### ISSUE THREAD

**Issue by chrisheinle** [react-native-community/react-native-maps#1991]
### Is this a bug report?

Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Steps to Reproduce

1. Use this code 
    
```
 const mapView = (
      <MapView
        style={styles.map}
        mapType={MAP_TYPES.NONE}
        provider={PROVIDER_GOOGLE}
        minZoomLevel={0}
        maxZoomLevel={4}
        region={this.state.region} >
        <MapView.UrlTile
          key="mvut1"
          urlTemplate={baseTilesUrl} />
      </MapView>);
    return (
      <View style={styles.mapContainer}>
        {mapView}
      </View>
    );
```

2. Use this styling:
```
  mapContainer: {
    ...StyleSheet.absoluteFillObject,
    top: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 0,
    zIndex: -1,
  },
  mapTiles: {
    ...StyleSheet.absoluteFillObject,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
```
3. Render the map into a container which does not have 100% screenHeight, e.g. below a nav-bar.
4. Zoom-out completely

### Expected Behavior

iOS and Android Map should fit 100% into the given container.

### Actual Behavior

Top and Bottom of the map will be cut off (around 5-10%).
!!! This only works on Android. On iOS, everything is displayed fine and the map is properly scaled.

### Reproducible Demo

Only works on an Android device, code given in the reproduction steps.

**Comment by alvelig** [comment]
Your code is not enough and it's not a demo. Fork https://github.com/alvelig/react-native-maps-example to reproduce your problem.

**Comment by Assem-Hafez** [comment]
I have the same problem, after a while of debugging i found that if the Mapview fills the screen everything works as expected. but if i tried to give a height to the map less than the screen height the cut increases from the top of the map. This happens when the zoom level is small (eg. 0), by increasing the zoom level you can reach additional part of the hidden area. I think that the mapview heigh is not reflected correctly on the native component. 

Can i help you with additional information ?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
