### ISSUE TITLE
Feature reuest maxExtend & wrapDateLine

### ISSUE THREAD

**Issue by hanselsen** [react-native-community/react-native-maps#2043]
### Environment

"react": "^16.0"
"react-native": "^0.51"
git+ssh://git@github.com/react-community/react-native-maps.git"

### Feature

Implementation for `maxExtend` and `wrapDateLine` for `LocalTile` layers.

### Why

Whilst projecting a local image on the map using `LocalTile`, limiting the image to be shown only once. So making sure the map is not infinite scrollable in the horizontal position and only show the Image.

### Example
```
<MapView
	ref={r => this.map = r}
	minZoomLevel={0}
	maxZoomLevel={4}
	rotateEnabled={false}
	pitchEnabled={false}
	wrapDateLine={false}
	provider={PROVIDER_DEFAULT}
	mapType={MAP_TYPES.NONE}>
	<LocalTile
		zIndex={-1}
		maxExtend={this.props.map.maxExtend}
		pathTemplate={this.props.map.tilePath}
		tileSize={this.props.map.tileSize}/>
</MapView>
```

**Comment by Stophface** [comment]
Getting the Mapextend, the covered area that is shown by the MapView would be awesome. That would increase the performance of `react-native-maps` dramatically because one can finally only render Marker, Polygons, Overlays, ... what is actually shown in the Mapextend instead of rendering everything all the time.
