### ISSUE TITLE
Reordering markers has no effect on the map

### ISSUE THREAD

**Issue by madox2** [react-native-community/react-native-maps#215]
I am trying to display multiple markers on the map where one can be selected (pin color is red). If there are markers close to each other I want selected marker to be in foreground.

I have tried to push selected marker to the end of the array in order to be rendered last:

``` javascript
render() {
  const { selected } = this.state;
  const points = [
    ...this.data.filter(p => p.id !== selected.id),
    ...this.data.filter(p => p.id === selected.id)
  ];
  return (
    <MapView style={styles.map} initialRegion={this.initialRegion} ref="map">
    {points.map(p => (
      <Marker
        pinColor={p.id === selected.id ? 'red' : 'blue'}
        onPress={() => this.onPointSelect(p)}
        coordinate={{ latitude: p.latitude, longitude: p.longitude }} />
    ))}
    </MapView>
  );
}
```

I can see that `points` has the expected order in log output, but order on the device remains the same.

I have also tried to add `key` property:

``` javascript
<Marker
  key={p.id}
  pinColor={p.id === selected.id ? 'red' : 'blue'}
  onPress={() => this.onPointSelect(p)}
  coordinate={{ latitude: p.latitude, longitude: p.longitude }} />
```

It doesn't work too and furthermore the color of marker is not changed on select. I suppose there is a bug when using `key` property because it doesn't re-render markers at all. I have tried this on android device.

Is there any other way how to force one marker to be displayed above others?

**Comment by benhoyt** [comment]
Yep, I'm seeing this exact same issue (and tried the same solution). Markers seem to have a bit of trouble updating in certain cases, for example, if you set a style attribute in a marker based on a prop, and then change the prop it won't update.

**Comment by benhoyt** [comment]
@madox2 FYI, I tried to hack around this issue per this [StackOverflow answer](http://stackoverflow.com/questions/14771569/google-maps-v2-marker-zordering-set-to-top/14771740#14771740) by creating a dummy callout and calling `.showCallout()`, but that doesn't seem to do anything either.

**Comment by jonesdar** [comment]
From what I can see the markers z-order increases from the top of the screen to the bottom regardless of specification order.
I think this is deliberate - so that when the user tilts the map with the two-finger drag, the markers overlap correctly based on distance from the user. In fact while tilted if you rotate the map you'll see that the markers dynamically change z-order to keep the closer ones on top.
It would be good if they followed the specification order when there's no tilt though.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
