### ISSUE TITLE
centerOffset equivalent in android

### ISSUE THREAD

**Issue by nomoreboredom** [react-native-community/react-native-maps#2173]
### Is this a bug report?

No, it is a question

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

    react-native: 0.53.4
    react: 16.2.0
	react-native-maps: 0.20.1

### Steps to Reproduce

In order to cluster all the markers at a specific coordinate and to avoid the markers to render on top of each other, I am applying a function to shift marker positions(not coordinates, just annotation view) depending on the marker count. 

Then, I apply those to centerOffset prop of the marker, and on IOS, the markers display spreaded, not on top of eachother as I want to achieve. As centerOffset is not working on android, I followed the part regarding anchoring, and I can calculate these anchor points, and although I can put the markers on correct positions, i need to increase the view distance between each marker. Anybody have any idea how to achieve this?

Thanks!

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
