### ISSUE TITLE
MapView.Circle intersection between the areas

### ISSUE THREAD

**Issue by Angelk90** [react-native-community/react-native-maps#2177]
### Is this a bug report?

No.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes.

### Environment

```
"react": "^16.3.0-alpha.1",
"react-native": "0.54.4",
"react-native-maps": "https://github.com/react-community/react-native-maps.git", (fetched yesterday).

```

### Expected Behavior

I have MapView.Circle, I have to make sure that when two or more of them meet, the part that is not in common is deleted.

Example I have a and b:
a and b have a certain coordinate, both are different, and have an equal radius.
These two circles, meet and have a part of a common area, I just have to show the part of the area they have in common and eliminate the remaining part.
A ∩ B
![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Venn_A_intersect_B.svg/350px-Venn_A_intersect_B.svg.png)

How could I do?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
