### ISSUE TITLE
[Android] Target API level will require API 26 (or greater) in August 2018 

### ISSUE THREAD

**Issue by MarkOSullivan94** [react-native-community/react-native-maps#2245]
The Android target API level will require API 26 (or greater) in August 2018 for new apps to be published, November 2018 for existing app to publish updates.

Currently I had a look at the gradle settings for the lib and it is at 25 and I think this could affect getting applications published on the Google Play store if it isn't changed before August (I would rather be safe than sorry and just update it in case it will cause issues for users of react-native-maps). 

If you are curious there is a PR waiting in the main React Native project for this same issue which can be found here: https://github.com/facebook/react-native/issues/18095

### Is this a bug report?

No, more so a warning / heads up.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

N/A

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Reproducible Demo

N/A

**Comment by rborn** [comment]
@MarkOSullivan94, @alvelig should we wait for the FB bug to be fixed?

**Comment by MarkOSullivan94** [comment]
If there has been no issues in the past reported because of RN-Maps using 25 which is different from RN (looks like it's using 22), then it might be okay to do this change before RN has it done.

Best to see what will happen if you integrate React Native Maps with target api 26 with a new React Native project to be safe though.

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
