### ISSUE TITLE
How to draw route between to points or Adding polyline on the maps

### ISSUE THREAD

**Issue by luoerming** [react-native-community/react-native-maps#2262]
**Is this a bug report?**
NO

**Have you read the Installation Instructions?**
Yes

**Environment**

` react-native: 0.51.0
react: 16.0.0
react-native-maps: 0.20.1`

**Steps to Reproduce**
1. git clone https://github.com/react-community/react-native-maps.git
2. cd react-native-maps/example
3. gem install bundler
4. npm install
5. npm run build:ios

**Expected Behavior**
I expect to show the planned route on the map

![map](https://user-images.githubusercontent.com/1733426/40097966-abfa7446-590b-11e8-97c6-ba41453442a1.jpg)

**Comment by adhavalboy** [comment]
check out this article https://medium.com/@princessjanf/react-native-maps-with-direction-from-current-location-ab1a371732c2

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with [the latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
