### ISSUE TITLE
Custom header support for UrlTile

### ISSUE THREAD

**Issue by ConradJChan** [react-native-community/react-native-maps#2293]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

"react": "16.3.1",
"react-native": "0.55.4",
"react-native-maps": "0.21.0",

### Steps to Reproduce

When using the `UrlTile` component, I have a requirement to send an Authorization header when querying the custom tiles but I haven't found a way to specify that.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
