### ISSUE TITLE
Touch event (TouchableOpacity and etc) doesn't work.

### ISSUE THREAD

**Issue by nzrin** [react-native-community/react-native-maps#2299]
I've encountered some strange issue after successfuly load MapMarker on my MayView.

I have 1 floating button on my MapView and touch event doesnt work for few seconds after MapMarker has been loaded. But the touch event for the marker works perfectly. 

The floating button works perfectly after I wait for few seconds. May I know what cause this issue?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
