### ISSUE TITLE
Toolbar and My Location button is not disabled when user doesn't have location permissions.

### ISSUE THREAD

**Issue by BasitAli** [react-native-community/react-native-maps#2315]
### Is this a bug report?

Yes.

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

react-native: 0.55.3
react: 16.2.0
Target Platform: Android (all versions)
react-native-maps: 0.20.1

### Steps to Reproduce

Initialize the map with `showsMyLocationButton={false}` and `toolbarEnabled={false}` but ask for the location permissions after the map is displayed.

### Expected Behavior

**Disabling** the button and the toolbar should not require location permissions

### Actual Behavior

The toolbar and my location button are visible when tapping on a marker or panning the map.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
