### ISSUE TITLE
Feature: Add carthage support

### ISSUE THREAD

**Issue by jamesone** [react-native-community/react-native-maps#2331]
### Is this a bug report?

No

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes

### Environment

```
"react": "^16.3.1",
"react-native": "^0.55.4",
"react-native-maps": "^0.19.0",
```

The package recently added an update which forces iOS developers to use Cocoapods.

Is there a possibility you could support Carthage? Is it on the roadmap? 

There's an issue here asking for Carthage support: https://issuetracker.google.com/issues/35827791 (not sure if this is related or not)

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
