### ISSUE TITLE
privacy policy aspects

### ISSUE THREAD

**Issue by robsonrobi** [react-native-community/react-native-maps#2354]
I have no issue, further a question. Your lib works really great. For our app we use Google Maps on Android systems and Apple Card for iOS. Regarding the privacy policy in europe i would like to know if there are any requests to Google or Apple from inside the app? 

For example using the google maps api at a website, each request to google sends the ip-adress of the user, so a user is not invinsible. Can you tell me how the process is inside the app regarding Apple and Google. That would be really really helpful.

Greetings

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
