### ISSUE TITLE
showsTraffic causes iOS app crashing

### ISSUE THREAD

**Issue by hashmatmuqbil** [react-native-community/react-native-maps#2366]
Hi,

I'm using the props showsTraffic and mapLayer on MapView but when I toggle between 'standard' and 'satellite' and then click on the button with showsTraffic prop the app crashes on iOS but it works fine on Android

### Is this a bug report?

(write your answer here) Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)

### Environment
"https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",
"https://registry.npmjs.org/react-native-maps/-/react-native-maps-0.19.0.tgz",

### Steps to Reproduce

(Write your steps here:)

1. 2. 3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by diego-antonelli** [comment]
I have the same issue in the latest version. To reproduce you need to set the type = 'satellite, showsTraffic = true and provider = null (default) in iOS.

**Comment by outaTiME** [comment]
@diego-antonelli same here im using Expo SDK 31 with react-native-maps 0.22.0 following your steps, this issue is probably still open @christopherdro.
