### ISSUE TITLE
[Android] Investigate car2go/AnyMaps to support Google, Baidu and OSM maps on same codebase

### ISSUE THREAD

**Issue by fqborges** [react-native-community/react-native-maps#2386]
### Is this a bug report?

No, this is an idea of an potential enhancement.

### Description
I stumbled with this lib https://github.com/car2go/AnyMaps. It claims to support the following:
- Does not depend on any map provider - you can even use it without Google Maps.
- Map provider can be changed at runtime.
- Easy to extend. New providers can be added without changing the existing code.
- Map providers supported out of the box: Google Maps, OpenStreet maps, Baidu maps.

Depending on the details and support of the required features, it would be possible to use this lib as infrastructure to support multiple maps, without pulling most of the complexity inside rn-maps codebase, at least for Android side of things.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
