### ISSUE TITLE
Issue with method animateToNavigation

### ISSUE THREAD

**Issue by Ostafen** [react-native-community/react-native-maps#2402]
I have an issue when I call the method animateToNavigation.
I get the following error:
"Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null obect reference".
All parameters are passed correctly and are valid, like in the provided example.

The dependecy in package.json it this one:
    "react-native-maps": "git+https://github.com/react-community/react-native-maps.git"
I also use expo sdk version 29 to run the project.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
