### ISSUE TITLE
animateToNavigation does not support zoom / region

### ISSUE THREAD

**Issue by dorshay6** [react-native-community/react-native-maps#2406]
Like said in the PR this module doesn't work with zoom level but animate to navigation method also does not support region which makes it unusable for us.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
