### ISSUE TITLE
Change the path of yoga in Podfile to prevent error in build phase

### ISSUE THREAD

**Issue by manweihuang** [react-native-community/react-native-maps#2409]
https://github.com/react-community/react-native-maps/blob/c3b380272ba7cfa93d430a58028984a88fed0990/example/ios/Podfile#L12

Change this line to
`pod 'yoga', path: "../../node_modules/react-native/ReactCommon/yoga"`

otherwise there will be error during build phase.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
