### ISSUE TITLE
iOS could not get the value of e.nativeEvent.coordinate.latitude

### ISSUE THREAD

**Issue by nc3816** [react-native-community/react-native-maps#2690]
### Is this a bug report?

(write your answer here)
Yes

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

(Write your answer here.)
Yes
### Environment

   react-native: 0.58.1
    react: 16.6.3
    react-native-maps: 0.23.0
### Steps to Reproduce

(Write your steps here:)

I tried to get the value of the coordinat.latitude for onCalloutPress

```
getTheCalloutCoord = (e) => {
        console.log(e.nativeEvent.coordinate.latitude);
        console.log(e.nativeEvent.coordinate.longitude);
}

render(){
          <MapView 
                    provider={PROVIDER_GOOGLE}
                    onCalloutPress={(e) => this.getTheCalloutCoord(e)}      
                    showsCompass={true}
                    zoomEnabled={true}
                    zoomControlEnabled={true}
                    toolbarEnabled={false}>
          </MapView>
}
```

### Expected Behavior

(Write what you thought would happen.)
Should be getting the value of the latitude and longitude. 
### Actual Behavior

(Write what happened. Add screenshots!)

It works on Android, but not works on iOS. 
For iOS, it will show up: Cannot read property "latitude" of undefined.

![image](https://user-images.githubusercontent.com/12981492/52501279-f9b16580-2bad-11e9-9bb7-6cb28940443f.png)

Any suggestion? Thank you!

**Comment by rborn** [comment]
As per manual the `onCalloutPress` event doesn't pass any data ( the fact that works for one platform is a coincidence I think)
I'd move the event to the markers and use the marker's info to get the coordinates.

**Comment by rborn** [comment]
@nc3816 still an issue or we can close it?

**Comment by nc3816** [comment]
> @nc3816 still an issue or we can close it?

You could close it, I gave up.

**Comment by nc3816** [comment]
@rborn You could close it, I didn't use it.

**Comment by rukmanary** [comment]
Hey, I'm handling a hands-on project, the previous developer only develop Android. Now, I continue to setup IOS and I am still getting this error but in different case. I am using the latest version and in my case, I want to get the coordinates from `<Callout />` onPress event. According to the documentation, onPress in Callout does not returns anything. But in my projects, the code goes like this:

```
<Marker {...props}>
      <Callout tooltip={true} onPress={this._onPressCallout}>
             <MyCustomToolTip />
      </Callout>
</Marker>
```

```
_onPressCallout = event => {
     console.log(event)
} 
```

For both Android & IOS,  it returning `SyntheticEvent` and has `nativeEvent` property. But the different is in Android, we can get `coordinate` property:
```
nativeEvent: {
  action: "callout-press"
  coordinate: {longitude: `my longitude value`, latitude: `my latitude value`}
  position: {y: 565, x: 360}
  __proto__: Object
}
```

But in IOS, I got `frame` instead of coordinate:
```
nativeEvent: {
  action: "callout-press"
  frame: {
    height: 96
    width: 274
    x: 81.66666666666666
    y: 259.3333333333333
    __proto__: Object
  }
  id: "unknown"
  point: {y: 21.333326975504576, x: 173.33333333333334}
  target: 6737
}
```

is it weird? Why I got the different returns for different Platform?  Your workaround @rborn is working but I provide button in my tool tip, so I want my users click on that not in the Marker.

Is this real bugs? Should I write new issue? Please help.
