### ISSUE TITLE
:react-native-maps:compileReleaseRenderscript FAILED

### ISSUE THREAD

**Issue by popadorin** [react-native-community/react-native-maps#2754]
Hello,

Having a issue with creating the apk at this point:

> Task :react-native-maps:compileReleaseRenderscript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-maps:releaseCompileClasspath'.
> Could not resolve com.android.support:support-compat:26.1.0.
  Required by:
      project :react-native-maps
   > Cannot find a version of 'com.android.support:support-compat' that satisfies the version constraints: 
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-vector-drawable:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:16.0.1' --> 'com.google.android.gms:play-services-basement:16.0.1' --> 'com.android.support:support-v4:26.1.0' --> 'com.android.support:support-compat:26.1.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:loader:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:16.0.1' --> 'com.google.android.gms:play-services-basement:16.0.1' --> 'com.android.support:support-v4:26.1.0' --> 'com.android.support:support-media-compat:26.1.0' --> 'com.android.support:support-compat:26.1.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:customview:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:viewpager:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:coordinatorlayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:drawerlayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:slidingpanelayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:swiperefreshlayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:asynclayoutinflater:28.0.0' --> 'com.android.support:support-compat:28.0.0'
        Constraint path 'rnWebstore:react-native-maps:unspecified' --> 'com.android.support:support-compat' strictly '26.1.0' because of the following reason: releaseRuntimeClasspath uses version 26.1.0
        Constraint path 'rnWebstore:react-native-maps:unspecified' --> 'com.android.support:support-compat' strictly '26.1.0' because of the following reason: releaseRuntimeClasspath uses version 26.1.0
        Constraint path 'rnWebstore:react-native-maps:unspecified' --> 'com.android.support:support-compat' strictly '26.1.0' because of the following reason: releaseRuntimeClasspath uses version 26.1.0

> Could not resolve com.android.support:support-annotations:26.1.0.
  Required by:
      project :react-native-maps
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints: 
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-compat:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:collections:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:cursoradapter:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-vector-drawable:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-compat:28.0.0' --> 'android.arch.lifecycle:runtime:1.1.1' --> 'com.android.support:support-annotations:26.1.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-compat:28.0.0' --> 'com.android.support:versionedparcelable:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:documentfile:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:loader:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:localbroadcastmanager:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.58.6' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:print:28.0.0' --> 'com.android.support:support-annotations:28.0.0'
        Dependency path 'rnWebstore:react-native-maps:unspecifi
....

I've run -  ./gradlew assembleRelease in /android folder

It worked until now, don't know what did I change because I didn't touch the configuration.

**Comment by novenix** [comment]
i have the exact same problem, i was working with everithing coool, and for some reason (i loose my project) i start a new one, when im installing the react native maps and make rebuild, i have this issue.
Cannot find a version of 'com.android.support:support-compat' that satisfies the version constraints: 
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-vector-drawable:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:16.0.1' --> 'com.google.android.gms:play-services-basement:16.0.1' --> 'com.android.support:support-v4:26.1.0' --> 'com.android.support:support-compat:26.1.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:loader:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:16.0.1' --> 'com.google.android.gms:play-services-basement:16.0.1' --> 'com.android.support:support-v4:26.1.0' --> 'com.android.support:support-media-compat:26.1.0' --> 'com.android.support:support-compat:26.1.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:customview:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:viewpager:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:coordinatorlayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:drawerlayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:slidingpanelayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:swiperefreshlayout:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Dependency path 'VisualRed:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.1' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-fragment:28.0.0' --> 'com.android.support:support-core-ui:28.0.0' --> 'com.android.support:asynclayoutinflater:28.0.0' --> 'com.android.support:support-compat:28.0.0'
   Constraint path 'VisualRed:react-native-maps:unspecified' --> 'com.android.support:support-compat' strictly '26.1.0' because of the following reason: debugRuntimeClasspath uses version 26.1.0
   Constraint path 'VisualRed:react-native-maps:unspecified' --> 'com.android.support:support-compat' strictly '26.1.0' because of the following reason: debugRuntimeClasspath uses version 26.1.0
   Constraint path 'VisualRed:react-native-maps:unspecified' --> 'com.android.support:support-compat' strictly '26.1.0' because of the following reason: debugRuntimeClasspath uses version 26.1.0

and says in sync

ERROR: Unable to resolve dependency for ':react-native-maps@debug/compileClasspath': Could not resolve com.android.support:support-compat:26.1.0.

**Comment by ohjeyong** [comment]
For what I understand, this issue will be solved in 0.24 version which is currently pre-release version. Maybe duplicate with #2737.

**Comment by rborn** [comment]
@popadorin please test with the master and let us know

**Comment by danniarreza** [comment]
@rborn I've tested using the master branch since last week and it seems to be working with no issue to me
