### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.lang.Iterable.iterator()' on a null object reference

### ISSUE THREAD

**Issue by denizbas92** [react-native-community/react-native-maps#2786]
It is a bug report.

    "react": "16.8.6",
    "react-native": "0.58.5",
     react-native-maps: 0.23.0

It is happening in Android native side. Application crashed in a class named  AirMapPolyline.java
at com.google.android.gms.maps.model.PolylineOptions.addAll(Unknown Source)

It happenned when I want to draw a polyline. It works in Ios, however it does not work in android
Is there any solution ?

**Comment by jahskee** [comment]
I got the same issue, is there a fix for this? Thanks

**Comment by alexandermckay** [comment]
I also have this issue.

**Comment by alexandermckay** [comment]
For anyone that comes across this issue it is not a bug.

The error is thrown whenever a Polyline or Polygon is given passed `undefined` to the coordinates prop.

Use something like `.filter()` to remove any undefined items before trying to render them and the error will be eliminated.

**Comment by swaxtic** [comment]
i got the same issue

**Comment by alexandermckay** [comment]
Someone just emailed me asking for further explanation, this was my response: 

Polyline or Polygon elements expect an array of LatLng objects, like this:

[{...}, {...}, {...}]

Now if instead of a LatLng object you have an element which is undefined, like this:

[{...}, undefined, {...}]

This will create an error.

To eliminate the error, you could do something like this:

const data = [{...}, undefined, {...}]

// identity when used as a predicate coerces undefined or null values to false

const identity = item => item

const filteredData = data.filter(identity)

// filteredData = [{...}, {...}]

No more null object reference :)

**Comment by altenfreelance** [comment]
I'm getting this same issue even without and undefined elements in the coordinates array.
