### ISSUE TITLE
Glitchy map controls

### ISSUE THREAD

**Issue by VinceBT** [react-native-community/react-native-maps#304]
On Android: 

Sometimes the "navigate to" button appears and sometimes it does not when a marker has been tapped. Also is it possible to move or disable the "center of user location" button on the top right corner ?

Kepp up the good work I love your module :+1:

**Comment by jrichardlai** [comment]
It seems its possible to hide the navigation button with `setMapToolbarEnabled` not sure why it would appear and disapear though... it seems pretty straightforward though, PR would be welcome! http://stackoverflow.com/questions/30430664/how-to-hide-navigation-and-gps-pointer-buttons-when-i-click-the-marker-on-th

**Comment by jrichardlai** [comment]
It seems its possible to hide the navigation button with `setMapToolbarEnabled` not sure why it would appear and disapear though... it seems pretty straightforward though, PR would be welcome! http://stackoverflow.com/questions/30430664/how-to-hide-navigation-and-gps-pointer-buttons-when-i-click-the-marker-on-th

**Comment by VinceBT** [comment]
Is there a way I can access the native map from your component in order to call the method ?

**Comment by kevinL5** [comment]
I'm interested in the answer too. I tried to set setMapToolbarEnabled to false in AirMapView.java but it's didn't worked.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
