### ISSUE TITLE
Android - Map continue to animate when I'm zooming

### ISSUE THREAD

**Issue by quentinncl** [react-native-community/react-native-maps#3147]
### Environment

```bash
Expo CLI 3.1.0 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: ^16.8.6 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-native-maps: ^0.25.0,
```

### Target
Android

### Steps to Reproduce

When I am zooming on the map, if I zoom too far, the map starts to animate itself and starts to descend slowly. The behavior is the same if I dragged the map down.

### Expected Behavior

I would like to, when I zoom to the max, the map don't move and I would like to store the new region.

### Already tried
- Remove `onRegionChangeComplete` : I have the expected behavior but I don't store the location.
- Change `onRegionChangeComplete` to `onRegionChange` : the map is shaking and I can't move.
- I thought it was due to expo, but i tried on a bare react native app but still have the problem

### Reproducible Demo

I created a snack [here](https://snack.expo.io/@quentinncl/f1e354)

**Comment by quentinncl** [comment]
No one can help me or has a workaround ? :/

**Comment by andrewtelkamp** [comment]
Can I ask why you're using `region` instead of `initialRegion`?

Without knowing more about your use-case I can't say for sure, but it sounds like this may be your issue. `initialRegion` will set the maps region when the map first loads, and that is it. `region` is only used when you have a need complete control over the maps region (and typically doesn't involve any user interaction).

You can still track and update the maps current region in state for whatever your use case might be, but you don't need to set the map's actual region every time you pan, it already knows what it's region is.

**Comment by quentinncl** [comment]
That was a mistake !!!!!!!! REALLY Thank you for your observation with `initialRegion` I have the behavior I wanted !!  thks so much !

**Comment by christopher-18** [comment]
@WarrenBuffering & @quentinncl  Can you also look into https://github.com/react-native-community/react-native-maps/issues/3545 and suggest some work around?
