### ISSUE TITLE
Remove code duplication between polygon/polyline/circle

### ISSUE THREAD

**Issue by lelandrichardson** [react-native-community/react-native-maps#38]
This could be improved a lot with polymorphism/inheritance.

**Comment by christopherdro** [comment]
@lelandrichardson Can you reference what is being duplicated?

**Comment by lelandrichardson** [comment]
@christopherdro if you look at the classes for Polygon and Polyline in both ios and android for this library, they are extremely similar. A lot of the props are identical for both classes, and a lot of the handling of adding them to the map etc is the same.

**Comment by americool** [comment]
Hey, reading through some of the issues and found this. Are there specific files you can suggest looking at? I'm interested in reading the source code and seeing if I can assist in anyway. (Also checking if this issue is still active.) Thanks!

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
