### ISSUE TITLE
followsUserLocation will zoom to user but not follow them

### ISSUE THREAD

**Issue by patrickml** [react-native-community/react-native-maps#421]
I am using the iOS simulator and at first the app requests to use my position -- i agree. Then i am setting the debug to the highway drive. I have `followUserLocation={true}` which is controlled by the state. The map zooms in on the user, but when the user moves the users marker goes off of the map and the map stands still.

**Comment by jasonmerino** [comment]
I am running into this issue in the iOS simulator as well. Adding the `showsUserLocation={true}` and `followsUserLocation={true}` props zooms to the users location initially, but then when the user changes location the region does not change to follow.

**Comment by CharlieIGG** [comment]
Hello @patrickml @jasonmerino, did you find a workaround for this?

**Comment by jasonmerino** [comment]
I haven't yet, but it's not a huge issue in the app I'm working on so I haven't looked into it too much.

**Comment by patrickml** [comment]
I did. I had to change some value in the iOS code but it really wasn't that
stable.

**Comment by Larney11** [comment]
Has anyone found the solution to this issue?

**Comment by peterept** [comment]
Bit hacky but I am re-centering the view in `navigator.geolocation.watchPosition`

**Comment by Larney11** [comment]
Yeah me too but it is a bit jumpy....

**Comment by raihanrazi** [comment]
Doing the same as @peterept and @Larney11. Definitely not the best solution out there.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
