### ISSUE TITLE
iOS markers with image can't drag and drop.

### ISSUE THREAD

**Issue by paulparton** [react-native-community/react-native-maps#474]
When I add am image to my markers they are no longer draggable in iOS. They still trigger an onPress event.

```
<MapView.Marker
     draggable
     image={require('./custom_marker.png')}
```

**Comment by paulparton** [comment]
Update on this, I was trying to get this working again and found that I can make it move by dragging from a space a little bit below the pin image

**Comment by adamjones353** [comment]
I am also having this issue and can confirm that the hitbox for custom markers is a small point bottom center.

**Comment by rafaeljimenez** [comment]
same problème...

**Comment by eard7** [comment]
Same probleme here

**Comment by jaspal747** [comment]
same problem.

**Comment by MiLeung** [comment]
same

**Comment by hkxicor** [comment]
same problem
any solution?

**Comment by Cantinaband** [comment]
i have currently the same problem. any solution?

**Comment by Matt-F-Wu** [comment]
I have the same problem. I have tried adding a children as this example suggested, but it doesn't actually work:
https://github.com/react-community/react-native-maps/blob/f553317fcaa2e3a4889f38c4bb2e215693f3f20c/example/examples/DraggableMarkers.js

I even tried adding the exact same component as they offered in the example, still no luck

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
