### ISSUE TITLE
onDragEnd / onMarkerDragEnd-events doesn't contain property "position"

### ISSUE THREAD

**Issue by ippa** [react-native-community/react-native-maps#520]
According to the documentation for MapView and MapView.Marker both onMarkerDragEnd and onDragEnd events should contain position - containing x and y where the marker was dropped.

From what I can see there's no such property.  On IOS, react-native 0.33.0-rc0, react-native-maps master. I've also tried older versions without any l luck. There is the "coordinate"-property containing longitude and latitude, but no "position". For example, I display a trashcan in the uperleft corner where I want to drop markers do delete them. For that I need a working position-prop.

**Comment by ippa** [comment]
I've confirmed this by debugging the included example "DraggableMarkers.js", checking into the "nativeEvent"-property. It contains "coordinate" but not "position" as the documentation says it should do.

**Comment by ippa** [comment]
any author feedback on this one? ping @spikebrehm. Running on master, still not getting position.

**Comment by ippa** [comment]
Doing some more testing I see that onMarkerDrag does contain "position"-property, but not onMarkerDragStart and onMarkerDragEnd

**Comment by gilbox** [comment]
For any PR heroes, it needs to be calculated here: https://github.com/airbnb/react-native-maps/blob/master/ios/AirMaps/AIRMapManager.m#L396

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
