### ISSUE TITLE
Polygon events

### ISSUE THREAD

**Issue by lopezjurip** [react-native-community/react-native-maps#55]
It is possible to add an event when a Polygon is pressed?

**Comment by lelandrichardson** [comment]
I would very much like to add this... I haven't been able to fine built-in support for this, though. I think we'd have to hack it in ourselves if we want it.  Seems possible, just not as easy as I wish it was.

Seems some people here have found ways to do it with mapkit:

http://stackoverflow.com/questions/20858108/detecting-touches-on-mkoverlay-in-ios7-mkoverlayrenderer

Also,  it looks like this is available as a newer API on google maps:

https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#setOnPolygonClickListener%28com.google.android.gms.maps.GoogleMap.OnPolygonClickListener%29

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
