### ISSUE TITLE
pointerEvents prop on MapView.Marker not working correctly

### ISSUE THREAD

**Issue by carleryd** [react-native-community/react-native-maps#550]
Setting pointerEvents to "auto" or "none" both disable onPress on the Marker and its children, and the option "box-none" isn't available at all. Is MapView.Marker extending a View? Where should I look to change this behavior?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by LaVielle** [comment]
Ran into this issue just now.

I try adding `pointerEvents="box-none"` prop to `<MapView.Marker>` and get the following error:
```
UIView base class does not support pointerEvent value: box-none
```

To reproduce:
```
<MapView.Marker
  pointerEvents="box-none"
  // otherProps
/>
```

"react-native": "0.59.9"
"react-native-maps": "0.25.0"

**Comment by pkt-dev** [comment]
Any update on this issue? I'm wanting to ignore the Marker onPress and have the MapView handle the onPress.

**Comment by riccardolardi** [comment]
Also interested in this since I'd like to ignore the default marker callout actions
