### ISSUE TITLE
[iOS] Change Callout Touch Region for Custom Marker?

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-maps#561]
Is there a way to adjust the callout touch region for a custom marker on iOS? `calloutAnchor` appears to be android-only, and right now I have to touch _above_ the marker to get the callout to pop up. Image below shows the touch region as a red square, I would like to be able to move this down so that it is over the marker itself:

<img width="195" alt="screen_shot_2016-09-09_at_10_51_10_am" src="https://cloud.githubusercontent.com/assets/4974609/18391351/bb64aba0-767b-11e6-9e3c-96f431e8c8fb.png">

**Comment by maluramichael** [comment]
I got this problem too pretty annoying when it is not working just for some pins.

**Comment by alvelig** [comment]
#1845 should solve this problem. Please comment if you tested and if there are any bugs detected, as collaborators ask me to have positive replies on my pull request to merge it to master.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
