### ISSUE TITLE
calling showCallout() triggers onMarkerSelect() event?

### ISSUE THREAD

**Issue by guofoo** [react-native-community/react-native-maps#62]
Upon calling showCallout() on a Maview Marker ref, I seem to receive the event onMarkerSelect() for that marker. The result is that the callout is selected twice (redrawn twice) Is this the current intended behavior? If so, is there a way to disable the even generation? Since calling showCallout() explicitly means I'm already aware of the marker selection and do not need it to be selected again.

**Comment by singhiam** [comment]
Hello Guys,

Hope you are doing great !

do you have ant update in this issue ?

**Comment by lucianomlima** [comment]
Same here using React Native 0.45.1 and react-native-maps 0.16.4 on iOS.
Android it's ok. Have a workaround to avoid this?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
