### ISSUE TITLE
Are GIFs supported in MapView.Marker's image prop?

### ISSUE THREAD

**Issue by jshaw22** [react-native-community/react-native-maps#68]
Regular images work fine, but gifs don't seem to. Would be nice to have this issue verified as we're trying to render blinking dots on multiple socket connections.

Thanks!!

**Comment by lelandrichardson** [comment]
Hmmm. I haven't tried this and I'm not really sure what I would need to change in order to get it. AFAICT the images should have the same compatibility as any local resource provided to the `<Image />` component.

**Comment by jshaw22** [comment]
Just verified this with native <Image /> component and the GIFs renders. Unfortunately it doesn't in MapView.Marker.Animated image prop :(.

**Comment by mbmelgo** [comment]
Can someone implement this? Thank you

**Comment by gilbox** [comment]
Map markers with image or any sort of complexity are pretty broken on android. I think we would need to improve android's marker implementation before adding something like this.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by jgabomination** [comment]
Rendering Gif files on React native Map View any work around
