### ISSUE TITLE
Feature request: ability to specify background color when tooltip=true

### ISSUE THREAD

**Issue by cy2cheng** [react-native-community/react-native-maps#70]
Would like to be able to pass in custom colors and margins when tooltip=true. :)

Thanks!

**Comment by jgibbons** [comment]
+1 this would be awesome

**Comment by narek11** [comment]
+1

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
