### ISSUE TITLE
Draggable Markers Impossible to Use on iOS?

### ISSUE THREAD

**Issue by steve-gray** [react-native-community/react-native-maps#714]
Is there a way to set the draggable region for an annotation/marker/image pin? It seems that the iOS default is to have the marker be insanely small - such that the pin is only draggable with a mouse and carefully aiming beneath the pin.

Any guidance on this would be appreciated, I can't seem to find how to deal with this through the API.

-Steve

**Comment by freshnewegg** [comment]
is there an update on this?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
