### ISSUE TITLE
Persistent callout

### ISSUE THREAD

**Issue by ahmed1490** [react-native-community/react-native-maps#73]
Is there a possibility of not having callout disappear?

I tried 

```
        <MapView.Marker draggable ref="m2"
          onDragStop={(e) => this.setState({ startMarker: e.nativeEvent.coordinate })}
          onDragStart={(e) => this.refs.m2.showCallout()}
          coordinate={this.state.startMarker}
        >
          <MapView.Callout>
            <View>
                <Text>This is a plain view</Text>
              </View>
          </MapView.Callout>
        </MapView.Marker>
```

this still seems to be making a fade even on drag start and stop..

**Comment by lelandrichardson** [comment]
@ahmed1490 this would be a good feature. Let me see if I can figure out how we could get this working.

**Comment by af7** [comment]
@lelandrichardson I am also interested to this, plus the other one that we discussed of the callout appearing automatically on map load. Do you think we could have these 2 features soon? Thank you for the consideration.

**Comment by rborn** [comment]
@hegelstad as soon as a community member will put the effort into making it 😔

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
