### ISSUE TITLE
[iOS, Google Maps] User location marker without transparency

### ISSUE THREAD

**Issue by stereodenis** [react-native-community/react-native-maps#759]
![iphone 5 ios 10 1 14b72 2016-11-01 21-06-11](https://cloud.githubusercontent.com/assets/1406461/19901150/33dec622-a077-11e6-968e-1a0e274082b8.png)

**Comment by btoueg** [comment]
I have this issue as well but on the simulator only, when running on a real device it looks fine.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
