### ISSUE TITLE
onRegionChangeComplete is called too many times, and not when really the event ends

### ISSUE THREAD

**Issue by cinder92** [react-native-community/react-native-maps#857]
This method is called when i not ended to pinch the map, is there anyway to fix this?

http://imgur.com/VtKeC1g

Here is the code

```
<MapView
	style={{flex:1}}
	region={{
	latitude: parseFloat(this.state.initialPosition.coords.latitude),
        longitude: parseFloat(this.state.initialPosition.coords.longitude),
	latitudeDelta,
	longitudeDelta,
	}}
	showsUserLocation={true}
	onRegionChangeComplete={(region) => {
	     console.log('onRegionChangeComplete called!');
	}}
/>
```

**Comment by saberking** [comment]
I used _.debounce to work around this, it is not perfect but still much better than nothing

**Comment by samer** [comment]
+1
facing the same issue

**Comment by thiphariel** [comment]
@saberking What do you mean by "I used _.debounce" ? Do you refer to `Lodash`?

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!

**Comment by Simek** [comment]
I'm experiencing same problems with `onRegionChangeComplete` being fired too many times and also during map move on latest version (`0.24.2`) on iOS. GIF form @cinder92 post shows the issue as it happens.
