### ISSUE TITLE
Request: Could you add optional parameters  to "fitToSuppliedMarkers()" like in "fitToCoordinates()"

### ISSUE THREAD

**Issue by chetnadaffodil** [react-native-community/react-native-maps#876]
The tip of the markers are being chopped off when adjusted to the new co-ordinates, like in the picture below:

Here is my code:

    focus=()=> {
        this.mapRef.fitToSuppliedMarkers([
                "Marker1",
                "Marker2",
            ], true);
    }

    componentDidMount() {
        animationTimeout = setTimeout(() => {
            this.focus();
        }, 2000);
    }

    componentDidUpdate() {
        animationTimeout = setTimeout(() => {
            this.focus();
        }, 2000);
    }

![help](https://cloud.githubusercontent.com/assets/17562095/21041556/c486bc40-be11-11e6-93b8-7a3ea9aaf030.png)

**Comment by mocon** [comment]
+1 - It would be fantastic if we could specify some padding on the edges of the map! Thanks for all your work on this library.

**Comment by christopherdro** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
