### ISSUE TITLE
Blurry Callout

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-maps#933]
I am using a custom callout component, and noticed that all of my callouts are very blurry. It looks as if the rendered result was rasterized as an image with pretty low resolution, and then scaled up in size. It's very noticeable, especially on retina screens. Thoughts?

![screen_shot_2017-01-04_at_8_53_18_am](https://cloud.githubusercontent.com/assets/4974609/21644508/c285e8ea-d25b-11e6-8390-6a35bcfec5c5.png)

**Comment by Mimicx** [comment]
nothing?

**Comment by Marswang92** [comment]
The same thing happened to me, any clue?

**Comment by Marswang92** [comment]
@joncursi any work around?

**Comment by Marswang92** [comment]
Temporary solved by not using built-in callout, but to use a flag to make selected marker render a tooltip with `position: 'absolute'`, will look into the source code to find a better solution.

**Comment by thymikee** [comment]
I'm having this issue as well. Did anybody find a solution to that? Or have an idea where to look to fix that in the source 😅

**Comment by thymikee** [comment]
The blurry text turned out to be a result of applying rotation transform on the map (it was animated from 180 to 360deg). Fixed by using 0 instead of 360deg on iOS. 
Hopefully that will help somebody. 

Not sure if it's fixable on the maps level, since it looks like an issue with anti aliasing, but that's just a guess.
