### ISSUE TITLE
If a polyline is one coordinate, it is not updated.

### ISSUE THREAD

**Issue by nrathi** [react-native-community/react-native-maps#962]
I have some code like this in my `render()` function. 

```
const {poyline} = currentResult; 
if (polyline) {
  polyline = <MapView.Polyline
  coordinates={polyline}
  strokeWidth={4}
  strokeColor={'#000'}/>;
}
```

As the current result is updated, the polyline is meant to be redrawn on the map. However, this does not happen if the polyline has exactly one coordinate (i.e., `polyline = [{lat: 30, lng: 30]}` and the old polyline remains on the map.

**Comment by rajeshkos** [comment]
Can you help me to draw polyline on android 

I am having this issue : 

https://github.com/airbnb/react-native-maps/issues/1095 


Please Help me

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
