### ISSUE TITLE
Customized map style not working.

### ISSUE THREAD

**Issue by percyteng** [react-native-community/react-native-maps#979]
Hey guys, I was trying to customize the map with a json array that I generated from the google map api style generator as referred in the documentation but somehow it is not working at all.

I have updated my react-native-maps to 0.12.4 as I noticed it is a new feature.

It broke my android so I'm just testing on iOS right now.

Anyone who has tried and succeded?

**Comment by percyteng** [comment]
I just got my android working and the map is working as expected.

So the issue is with iOS. react-native 0.38.1 and react 15.4.1

**Comment by haunguyen-agilityio** [comment]
hi all, i face with this issues too. Any update?

**Comment by haunguyen-agilityio** [comment]
@percyteng is your project working?

**Comment by henocdz** [comment]
I'm facing the same issue on iOS with: 

**React Native:** 0.41.2
**React Native Maps:** 0.13.0

On Android everything is working.

**Comment by ABleas** [comment]
I just got started with react-native-maps but I also can't get my styles to work on iOS. I haven't tried Android yet.

I wonder if I need to switch to / enable google maps, instead of the default map renderer on iOS? Are json styles supported out of the box on iOS? Thanks!

**Comment by rborn** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/react-native-community/react-native-maps/releases).

Thank you!
